# Generated by Django 3.0.5 on 2020-05-04 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='https://github.com/ninjananjo/'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_created',
        ),
        migrations.AddField(
            model_name='job',
            name='date_completed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='project_name',
            field=models.CharField(default='my project', max_length=100),
        ),

    ]
