# Generated by Django 3.0.6 on 2020-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200505_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(default='https://github.com/ninjananjo/', null=True),
        ),
    ]
