# Generated by Django 3.0.6 on 2020-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
